In [1]:
import torch
import numpy
print(torch.__version__)
print(numpy.__version__)
torch.cuda.is_available()

1.12.0+cu116
1.23.1


True

In [3]:
x = torch.empty(4,2)
print(x)

tensor([[4.2251e-05, 6.7134e-07],
        [1.3074e+22, 2.6311e+20],
        [5.3782e+22, 1.0871e-05],
        [4.3679e-05, 2.7150e-06]])


In [4]:
x = torch.rand(4, 2)
print(x)

tensor([[0.1616, 0.3230],
        [0.3177, 0.3536],
        [0.3800, 0.3699],
        [0.2159, 0.4635]])


self.long() is equivalent to self.to(torch.int64)

In [5]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [7]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


TORCH.TENSOR.NEW_ONES

Returns a Tensor of size size filled with 1. By default, the returned Tensor has the same torch.dtype and torch.device as this tensor.

TORCH.TENSOR.DOUBLE

self.double() is equivalent to self.to(torch.float64)

In [8]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [13]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.6374, -0.5044,  0.1426,  1.0584],
        [-0.3501,  0.3227,  0.7758, -1.8916]])


In [15]:
y = torch.rand(2,4)
print(y)

tensor([[0.6198, 0.0490, 0.2527, 0.2988],
        [0.6551, 0.4138, 0.4409, 0.0529]])


In [18]:
print(x + y)
print(torch.add(x, y))

tensor([[-1.0176, -0.4554,  0.3953,  1.3571],
        [ 0.3050,  0.7365,  1.2167, -1.8387]])
tensor([[-1.0176, -0.4554,  0.3953,  1.3571],
        [ 0.3050,  0.7365,  1.2167, -1.8387]])


In [19]:
y.add_(x) #y += x

tensor([[-1.0176, -0.4554,  0.3953,  1.3571],
        [ 0.3050,  0.7365,  1.2167, -1.8387]])

In [21]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4],
                  [6,8]])
print(torch.mm(x,y)) #(1*2)+(3*6)

tensor([[20., 28.],
        [52., 76.]])


In [23]:
print(x)

tensor([[1., 3.],
        [5., 7.]])


In [24]:
print(x[:,1])

tensor([3., 7.])


In [27]:
x = torch.randn(4,5)
y = x.view(20)
z = x.view(5,-1)

print(x)
print(y)
print(z)

tensor([[ 0.8325,  0.9705, -0.9409, -0.2729, -0.7319],
        [-0.2335,  0.3574, -1.7165,  0.5418, -0.7865],
        [ 0.9549, -0.9734, -0.5038, -0.9493, -0.3297],
        [-2.1688,  1.2235, -0.1438, -1.0460, -1.2150]])
tensor([ 0.8325,  0.9705, -0.9409, -0.2729, -0.7319, -0.2335,  0.3574, -1.7165,
         0.5418, -0.7865,  0.9549, -0.9734, -0.5038, -0.9493, -0.3297, -2.1688,
         1.2235, -0.1438, -1.0460, -1.2150])
tensor([[ 0.8325,  0.9705, -0.9409, -0.2729],
        [-0.7319, -0.2335,  0.3574, -1.7165],
        [ 0.5418, -0.7865,  0.9549, -0.9734],
        [-0.5038, -0.9493, -0.3297, -2.1688],
        [ 1.2235, -0.1438, -1.0460, -1.2150]])


In [28]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.7252])
0.7252404093742371
torch.float32


In [29]:
x = torch.randn(2)
print(x)

tensor([-1.0933, -0.2635])


item() can extract only one scalar

In [30]:
print(x.item())

ValueError: only one element tensors can be converted to Python scalars

In [31]:
tensor = torch.rand(1, 3, 3) # 3 dimension
print(tensor)
print(tensor.shape)

t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[[0.1549, 0.9954, 0.4358],
         [0.9675, 0.2141, 0.5993],
         [0.2213, 0.8787, 0.7652]]])
torch.Size([1, 3, 3])
tensor([[0.1549, 0.9954, 0.4358],
        [0.9675, 0.2141, 0.5993],
        [0.2213, 0.8787, 0.7652]])
torch.Size([3, 3])


In [32]:
t = tensor.unsqueeze(dim=0)
print(t)
print(t.shape)

tensor([[[[0.1549, 0.9954, 0.4358],
          [0.9675, 0.2141, 0.5993],
          [0.2213, 0.8787, 0.7652]]]])
torch.Size([1, 1, 3, 3])


In [34]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([1,4])
z = torch.FloatTensor([1,4])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [1., 4.],
        [1., 4.]])


In [35]:
a = torch.randn(1, 1, 3, 3)
b = torch.randn(1, 1, 3, 3)
c = torch.cat((a,b), dim=0)

print(c)
print(c.size())

tensor([[[[-0.2579, -0.1175,  0.9612],
          [ 1.0278,  1.5451, -1.1229],
          [-1.7517, -1.3157, -0.0370]]],


        [[[ 1.0278,  0.0206, -0.0933],
          [-1.3338, -0.6957, -0.5234],
          [-0.9263, -1.8338, -1.8048]]]])
torch.Size([2, 1, 3, 3])


In [36]:
a = torch.randn(1, 3, 3)
b = torch.randn(1, 3, 3)
c = torch.cat((a,b), dim=0)

print(c)
print(c.size())

tensor([[[ 0.7629,  0.8261,  0.6061],
         [-0.8260, -0.7346, -0.2523],
         [-0.3283,  0.1293, -0.6384]],

        [[ 0.6722,  0.3604,  0.2858],
         [ 1.4664,  1.4813, -0.2243],
         [-0.9979, -0.6393,  0.2671]]])
torch.Size([2, 3, 3])


In [37]:
a = torch.randn(1, 3, 3)
b = torch.randn(1, 3, 3)
c = torch.cat((a,b), dim=1)

print(c)
print(c.size())

tensor([[[ 0.3434, -0.7073, -0.2052],
         [ 0.4547, -1.9578,  0.7714],
         [ 1.2634, -1.0574,  2.5056],
         [-0.3482,  1.3135, -0.5961],
         [ 0.0775,  1.6019, -1.3745],
         [-0.3630, -0.9014,  1.2045]]])
torch.Size([1, 6, 3])


In [38]:
a = torch.randn(1, 3, 3)
b = torch.randn(1, 3, 3)
c = torch.cat((a,b), dim=2)

print(c)
print(c.size())

tensor([[[-1.6983,  0.1502,  0.5657,  1.1365, -0.2098, -1.8873],
         [ 2.1066, -0.1699,  1.0551,  0.7999,  0.1805,  1.2036],
         [ 0.4179,  0.3578,  0.7410,  1.1297,  0.6931,  0.8618]]])
torch.Size([1, 3, 6])


Divide dimensions by 3

In [40]:
tensor = torch.rand(3, 6)
t1, t2, t3 = torch.chunk(tensor, 3, dim =1)

print(tensor)
print(t1)
print(t2)
print(t3)

tensor([[0.0152, 0.8873, 0.0334, 0.7959, 0.7652, 0.8113],
        [0.2054, 0.8310, 0.0062, 0.2904, 0.9101, 0.5908],
        [0.3354, 0.3309, 0.1251, 0.1279, 0.1227, 0.6131]])
tensor([[0.0152, 0.8873],
        [0.2054, 0.8310],
        [0.3354, 0.3309]])
tensor([[0.0334, 0.7959],
        [0.0062, 0.2904],
        [0.1251, 0.1279]])
tensor([[0.7652, 0.8113],
        [0.9101, 0.5908],
        [0.1227, 0.6131]])


Split : Size of tensors (Not divide by)

In [41]:
tensor = torch.rand(3,6)
t1, t2 = torch.split(tensor, 3, dim=1)

print(tensor)
print(t1)
print(t2)

tensor([[0.8730, 0.7641, 0.3796, 0.5922, 0.5371, 0.9999],
        [0.6336, 0.1352, 0.3545, 0.1777, 0.1803, 0.9061],
        [0.1242, 0.8783, 0.8131, 0.1330, 0.2199, 0.3187]])
tensor([[0.8730, 0.7641, 0.3796],
        [0.6336, 0.1352, 0.3545],
        [0.1242, 0.8783, 0.8131]])
tensor([[0.5922, 0.5371, 0.9999],
        [0.1777, 0.1803, 0.9061],
        [0.1330, 0.2199, 0.3187]])


In [3]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [4]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


Tensor

data: tensor형태의 데이터

grad: data가 겨쳐온 layer에 대한 미분값 저장

grad_fn: 미분값을 계산한 함수에 대한 정보 저장 (어떤 함수에 대해서 backprop 했는지)

requires_grad 속성을 True로 설정하면, 해당 텐서에서 이루어지는 모든 연산들을 추적하기 시작

계산이 완료된 후, .backward()를 호출하면 자동으로 gradient를 계산할 수 있으며, .grad 속성에 누적됨

기록을 추적하는 것을 중단하게 하려면, .detach()를 호출하여 연산기록으로부터 분리

기록을 추적하는 것을 방지하기 위해 코드 블럭을 with torch.no_grad():로 감싸면 gradient는 필요없지만, requires_grad=True로 설정되어 학습 가능한 매개변수를 갖는 모델을 평가(evaluate)할 때 유용

Autograd 구현에서 매우 중요한 클래스 : Function 클래스

In [1]:
import torch
x = torch.ones(3, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [2]:
y = x + 5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [3]:
print(y.grad_fn)

In [4]:
z =  y * y * 2
out = z.mean()
print(z, out)

tensor([[72., 72., 72.],
        [72., 72., 72.],
        [72., 72., 72.]], grad_fn=<MulBackward0>) tensor(72., grad_fn=<MeanBackward0>)


requires_grad_(...)는 기존 텐서의 requires_grad값을 바꿔치기(in-place)하여 변경

In [8]:
a = torch.randn(3,3)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True


기울기(Gradient)
역전파: .backward()를 통해 역전파 계산 가능

In [9]:
out.backward()

In [10]:
print(x.grad)

tensor([[2.6667, 2.6667, 2.6667],
        [2.6667, 2.6667, 2.6667],
        [2.6667, 2.6667, 2.6667]])


In [13]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 0.8241,  1.1607, -0.5850], requires_grad=True)
tensor([ 843.8942, 1188.5480, -599.0236], grad_fn=<MulBackward0>)


In [14]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([ 102.4000, 1024.0000,    1.0240])


자동 미분 흐름 다시 보기(1)
계산 흐름
a→b→c→out

∂out∂a=?
backward()를 통해

a←b←c←out 을 계산하면
∂out∂a 값이 a.grad에 채워짐

In [15]:
import torch
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [26]:
a = torch.ones(2, 2, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [27]:
print("a.data", a)
print("a.grad", a.grad)
print("a.grad_fn", a.grad_fn)

a.data tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
a.grad None
a.grad_fn None


In [28]:
b = a + 2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [29]:
c = b**2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [30]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [31]:
out.backward()
print("a.data", a)
print("a.grad", a.grad)
print("a.grad_fn", a.grad_fn)

a.data tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
a.grad tensor([[6., 6.],
        [6., 6.]])
a.grad_fn None


In [32]:
print("b.data", b)
print("b.grad", b.grad)
print("b.grad_fn", b.grad_fn)

b.data tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
b.grad None
b.grad_fn <AddBackward0 object at 0x0000017018242D30>


C:\Users\pjm98\PycharmProjects\pytorch_image\venv\lib\site-packages\torch\_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:482.)
  return self._grad


In [33]:
print("c.data", c)
print("c.grad", c.grad)
print("c.grad_fn", c.grad_fn)

c.data tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)
c.grad None
c.grad_fn <PowBackward0 object at 0x00000170172E6670>


C:\Users\pjm98\PycharmProjects\pytorch_image\venv\lib\site-packages\torch\_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:482.)
  return self._grad


In [34]:
print("out.data", out)
print("out.grad", out.grad)
print("out.grad_fn", out.grad_fn)

out.data tensor(36., grad_fn=<SumBackward0>)
out.grad None
out.grad_fn <SumBackward0 object at 0x000001706AEA3FD0>


C:\Users\pjm98\PycharmProjects\pytorch_image\venv\lib\site-packages\torch\_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:482.)
  return self._grad


## nn & nn.functional
두 패키지가 같은 기능이지만 방식이 조금 다름

위의 autograd 관련 작업들을 두 패키지를 통해 진행할 수 있음

텐서를 직접 다룰 때 requires_grad와 같은 방식으로 진행할 수 있음

결론적으로, torch.nn은 attribute를 활용해 state를 저장하고 활용하고,
torch.nn.functional로 구현한 함수의 경우에는 인스턴스화 시킬 필요 없이 사용이 가능

## nn 패키지
주로 가중치(weights), 편향(bias)값들이 내부에서 자동으로 생성되는 레이어들을 사용할 때

따라서, weight값들을 직접 선언 안함
예시

Containers

Convolution Layers

Pooling layers

Padding Layers

Non-linear Activations (weighted sum, nonlinearity)

Non-linear Activations (other)

Normalization Layers

Recurrent Layers

Transformer Layers

Linear Layers

Dropout Layers

Sparse Layers

Distance Functions

Loss Functions

In [36]:
import torch
import torch.nn as nn

In [38]:
m = nn.Conv2d(16, 33, 3, stride=2)
m = nn.Conv2d(16, 33, (3, 5), stride=(2,1), padding=(4,2))
m = nn.Conv2d(16, 33, (3, 5), stride=(2,1), padding=(4,2), dilation=(3,1)) #dilation는 패딩 사이의 간격

input = torch.randn(20, 16, 50, 100)
print(input)
output = m(input)
print(output)

tensor([[[[ 3.4544e-01, -6.7082e-02, -5.2966e-01,  ...,  6.7880e-01,
           -3.2373e-01,  4.2794e-01],
          [-1.1754e+00,  5.1228e-01, -7.4649e-01,  ..., -9.0243e-01,
           -1.0631e+00,  1.1820e+00],
          [-6.4549e-01,  2.0090e-01, -2.3482e-01,  ...,  3.2799e-01,
            1.3873e+00, -2.2724e-01],
          ...,
          [-3.1855e-02, -2.1912e-01,  1.4961e+00,  ..., -7.8725e-02,
           -1.9245e+00,  1.7191e+00],
          [ 1.8861e+00,  3.9927e-01, -2.4903e-01,  ...,  2.0241e+00,
            8.2510e-01,  3.0530e-02],
          [ 1.2742e+00, -5.8601e-01, -1.0199e+00,  ..., -4.2455e-01,
            1.7671e-01, -2.0260e-01]],

         [[-1.0445e+00,  5.7953e-01,  2.9674e-01,  ...,  6.2609e-01,
            1.7465e+00, -4.1992e-01],
          [-6.9096e-02,  7.8954e-02,  6.5288e-01,  ...,  9.6059e-01,
           -1.3862e+00,  1.2550e+00],
          [-7.8445e-01, -2.6093e+00, -5.9307e-01,  ..., -1.1858e-01,
           -1.5006e-01,  8.7295e-02],
          ...,
     

In [39]:
output.shape

torch.Size([20, 33, 26, 100])

In [40]:
import torch
import torch.nn.functional as F

In [41]:
filters = torch.randn(8, 4, 3, 3)
inputs = torch.randn(1, 4, 5, 5)
conv = F.conv2d(inputs, filters, padding=1)
conv.shape

torch.Size([1, 8, 5, 5])